---
title: "Rona Gif"
output: html_notebook
---

```{r}
library(tidyverse)
library(gganimate)
library(tidycensus)
options(scipen = 999)

theme_bluelabs <- theme_minimal()+
  theme(text = element_text(family = 'Avenir Next', size = 12),
        plot.title = element_text(hjust = 0.5, face=c('bold')),
        plot.margin = unit(rep(.5,4),"cm"),
        panel.grid = element_blank())

theme_set(theme_bluelabs)

apply_labels <- function(x, type_of = c('gen','swing')){
  if(type_of == 'gen'){
    new_x <- case_when(x == 'a' ~ '> 30%',
                       x == 'b' ~ '30% - 45%',
                       x == 'c' ~ '45% - 55%',
                       x == 'd' ~ '55% - 70%',
                       x == 'e' ~ '< 70%')
    new_x <- factor(new_x, levels = c('> 30%','30% - 45%',
                                      '45% - 55%','55% - 70%',
                                      '< 70%'))
  } else {
    new_x <- case_when(x == 'a' ~ 'GOP Gain\n> 10%',
                       x == 'b' ~ 'GOP Gain\n> 5%',
                       x == 'c' ~ 'Little\nSwing',
                       x == 'd' ~ 'Dems Gain\n> 5%',
                       x == 'e' ~ 'Dems Gain\n> 10%')
    new_x <- factor(new_x, levels = c('GOP Gain\n> 10%','GOP Gain\n> 5%',
                                      'Little\nSwing','Dems Gain\n> 5%',
                                      'Dems Gain\n> 10%'))
  }
  return(new_x)
}

all_fifty_states <- c(state.abb,'DC')
total_population <- get_acs(state = all_fifty_states, geography = "county", variables = "B01001_001", year = 2018)%>%
  mutate(pop_total = estimate)%>%
  select(state_county_fips = GEOID, pop_total)

incidence_county_day_init <- read_csv('https://raw.githubusercontent.com/joshyazman/random-projects/master/Rona%20x%20Politics%20GIFs/combined_nyt_cnty.csv')

county_results <- read_delim('https://raw.githubusercontent.com/joshyazman/random-projects/master/Rona%20x%20Politics%20GIFs/countypres_2000-2016.tab', delim = '\t')%>%
  filter(party %in% c('democrat','republican'),
         year %in% c(2008,2012,2016),
         office == 'President')%>%
  group_by(state, county, year)%>%
  mutate(twoway_votes = sum(candidatevotes))%>%
  ungroup()%>%
  filter(party == 'democrat')%>%
  mutate(dem_twoway = candidatevotes/twoway_votes,
         state_name = tolower(state),
         state_county_fips = stringr::str_pad(FIPS,5,side = 'left', pad = '0'))%>%
  group_by(year, state_name, state_code = state_po, state_county_fips)%>%
  summarise(dem_votes = sum(candidatevotes), tot_votes = sum(totalvotes), twoway_votes = sum(twoway_votes))%>%
  mutate(dem_twoway = dem_votes/twoway_votes)

incidence_by_week <- total_population%>%
  inner_join(county_results)%>%
  left_join(incidence_county_day_init)%>%
  mutate(twoway_16_label = apply_labels(twoway_16_cat),
         obama_trump_label = apply_labels(obama_trump_cat,'swing'),
         incidence_week = lubridate::floor_date(date,'weeks'))%>%
  filter(state_county_fips != '51019',
         date >= as.Date('2020-03-01'))%>%
  left_join(total_population)

View(incidence_county_day_init)
```

Definte the plotting function
```{r}
# Vectors of possible states/regions to filter to
all_states <- c('US',unique(incidence_by_week$state_code))
all_regions <- c('US',unique(incidence_by_week$region))

plot_outcomes <- function(state_code_filter = all_states, 
                          region_filter = all_regions,
                          pop_adjustment = c('n','y')) {
  if(state_code_filter == 'US' & region_filter == 'US') {
    incidence_county_day_init_filtered <- incidence_by_week
    
    subtitle_text <- element_blank()
    
  } else if (state_code_filter != 'US' & region_filter == 'US') {
    incidence_county_day_init_filtered <- incidence_by_week%>%
      filter(state_code %in% state_code_filter)
    
    subtitle_text <- paste0('States Included: ', paste(state_code_filter, collapse = ', '))
    
  } else if (state_code_filter == 'US' & region_filter != 'US') {
    incidence_county_day_init_filtered <- incidence_by_week%>%
      filter(region %in% region_filter)
    
    subtitle_text <- paste0('Regions Included: ', paste(region_filter, collapse = ', '))
    
  } else {
    print(paste0('Options for states are: ', all_states, collapse(', ')))
    print(paste0('Options for regions are: ', all_regions, collapse(', ')))
    break
  }
  
  weekly_by_hrc <- incidence_county_day_init_filtered %>%
    mutate(metric = 'Cases by 2016 Clinton Support')%>%
    select(incidence_week, metric, state_county_fips, 
           result = twoway_16_label, order_var = twoway_16_cat, 
           new_cases, pop_total)%>%
    group_by(metric, incidence_week, result, order_var)%>%
    summarise(new_cases_per_cap = sum(new_cases)/sum(pop_total),
              new_cases = sum(new_cases))%>%
    group_by(metric, incidence_week)%>%
    mutate(pct_new_cases = new_cases/sum(new_cases),
           pct_new_cases_per_voter = new_cases_per_cap/sum(new_cases_per_cap))%>%
    ungroup()
  
  weekly_by_ots <- incidence_county_day_init_filtered %>%
    mutate(metric = 'Cases by Obama - Trump Swing') %>%
    select(incidence_week, metric, state_county_fips, 
           result = obama_trump_label, order_var = obama_trump_cat, 
           new_cases, pop_total)%>%
    group_by(metric, incidence_week, result, order_var)%>%
    summarise(new_cases_per_cap = sum(new_cases)/sum(pop_total),
              new_cases = sum(new_cases))%>%
    group_by(metric, incidence_week)%>%
    mutate(pct_new_cases = new_cases/sum(new_cases),
           pct_new_cases_per_voter = new_cases_per_cap/sum(new_cases_per_cap))%>%
    ungroup()
  
  weekly_spine <- weekly_by_hrc%>%
    distinct(incidence_week, order_var)
  
  pop_by_hrc <- incidence_county_day_init_filtered %>%
    mutate(metric = 'Population by 2016 Clinton Support')%>%
    distinct(metric, result = twoway_16_label, 
             order_var = twoway_16_cat, 
             pop_total, state_county_fips)%>%
    group_by(metric, result, order_var)%>%
    summarise(pop_total = sum(pop_total))%>%
    group_by(metric)%>%
    mutate(pct_of_pop = pop_total/sum(pop_total))%>%
    ungroup()%>%
    right_join(weekly_spine, by = 'order_var')%>%
    select(metric, incidence_week, result, order_var, 
           new_cases_per_cap = pop_total, new_cases = pop_total,
           pct_new_cases = pct_of_pop, 
           pct_new_cases_per_voter = pct_of_pop)
  
  pop_by_ots <- incidence_county_day_init_filtered %>%
    mutate(metric = 'Population by Obama - Trump Swing')%>%
    distinct(metric, result = obama_trump_label, 
             order_var = obama_trump_cat, 
             pop_total, state_county_fips)%>%
    group_by(metric, result, order_var)%>%
    summarise(pop_total = sum(pop_total))%>%
    group_by(metric)%>%
    mutate(pct_of_pop = pop_total/sum(pop_total))%>%
    ungroup()%>%
    right_join(weekly_spine, by = 'order_var')%>%
    select(metric, incidence_week, result, order_var, 
           new_cases_per_cap = pop_total, new_cases = pop_total,
           pct_new_cases = pct_of_pop, 
           pct_new_cases_per_voter = pct_of_pop)
  
  all_metrics <- list(weekly_by_hrc, weekly_by_ots, pop_by_hrc, pop_by_ots)
  
  plot_df <- bind_rows(all_metrics)
  
  if(pop_adjustment == 'y'){
    title_text <- 'Share of Weekly New Cases per Voter by County-Level Election Result'
    p <- ggplot(plot_df, aes(x = result, y = pct_new_cases_per_voter, fill = order_var))+
      facet_wrap(~metric, scales = 'free', nrow = 2)+
      scale_fill_manual(values = c("#c41231","#C47F85","#F0F0F0","#208DFC","#124f8c"), guide = FALSE)+
      geom_col()+
      labs(title = title_text,
           subtitle = subtitle_text,
           caption = 'Date: {frame_time}\nSource: NYT',
           x = element_blank(),
           y = element_blank())+
      scale_y_continuous(labels = scales::percent, limits = c(0,.8))+ 
      transition_time(incidence_week)
  } else {
    title_text <- 'Share of Weekly New Cases by County-Level Election Result'
    p <- ggplot(plot_df, aes(x = result, y = pct_new_cases, fill = order_var, group = incidence_week))+
      facet_wrap(~metric, scales = 'free', nrow = 2)+
      scale_fill_manual(values = c("#c41231","#C47F85","#F0F0F0","#208DFC","#124f8c"), guide = FALSE)+
      geom_col()+
      labs(title = title_text,
           subtitle = subtitle_text,
           caption = 'Date: {frame_time}\nSource: NYT',
           x = element_blank(),
           y = element_blank())+
      scale_y_continuous(labels = scales::percent, limits = c(0,.8))+ 
      transition_time(incidence_week)  
  }
  
  p_anim <- animate(p, width = 800, height = 350, end_pause = 2, start_pause = 2)
  anim_save(filename = paste0('/Users/joshyazman/Desktop/covid-political-analysis/plots/',title_text, subtitle_text,'.gif'))
}
```

Explore!
```{r}
plot_outcomes()
plot_outcomes(state_code_filter = 'Texas')
plot_outcomes(state_code_filter = 'Michigan')
plot_outcomes(state_code_filter = 'Florida')
plot_outcomes(region_filter = c('Deep South','Peripheral South'))
plot_outcomes(region_filter = c('Deep South'))
plot_outcomes(region_filter = c('Plains'))
plot_outcomes(region_filter = c('Rocky Mountain'))
```
